name: TerraformGenerator
author: Hex_27
version: 9.0.0
api-version: 1.16
description: World Generator
main: org.terraform.main.TerraformGeneratorPlugin
load: startup
commands:
  terraform:
    description: Main command
    aliases: terra